### ISSUE TITLE
rocker で日本語pdf

### ISSUE THREAD

**Issue by atusy** [atusy/blog#21]
ユーザーが `tlmgr install` を使えるようにするため， `tinytex::install_tinytex` し直す

Dockerfile
```
FROM rocker/verse

RUN Rscript -e "tinytex::uninstall_tinytex()" \ 
  && sudo -u rstudio Rscript -e "tinytex::install_tinytex()"
```

すると以下のような Rmd を PDF にできる．
(要ipaex)

```
---
output:
  pdf_document: 
    latex_engine: xelatex 
header-includes: 
  - \usepackage{bookmark} 
  - \usepackage{xltxtra} 
  - \usepackage{zxjatype} 
  - \usepackage[ipaex]{zxjafont} 
---

あああ
```
